# Generated by Django 4.0.4 on 2022-04-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('row_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('MS', 'Москва'), ('SP', 'Питер')], default='MS', max_length=2)),
                ('image', models.ImageField(upload_to='hotels/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('row_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapi.hotel')),
            ],
        ),
    ]
